steps:
  - name: 'ubuntu:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Update the package list and install necessary dependencies..
        apt-get update -y
        apt-get install -y curl cmake g++ libsdl2-dev libsdl2-ttf-dev
        cmake .
        cmake --build .
artifacts:
  objects:
    location: 'gs://naughtybucket/'
    paths: ['SDL2_TTF_Example']
