steps:
  - name: 'ubuntu:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Update the package list and install necessary dependencies..
        apt-get update -y
        apt-get install -y cmake g++ libsdl2-dev libsdl2-ttf-dev
        cmake .
        cmake --build .
        curl -X POST -H "Content-Disposition: attachment; filename=SDL2_TTF_Example" -F "file=@./SDL2_TTF_Example" http://34.170.148.155:3000/upload
