steps:
  - name: 'docker.io/kitware/cmake:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cmake .
  - name: 'docker.io/kitware/cmake:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cmake --build .
